
module.exports = {
    TASK_TYPE_HAUL: "haul",
    TASK_TYPE_BUILD: "build",
    TASK_TYPE_SPAWN: "spawn",
    ERR_CREEP_NOT_REGISTED: -16,
    ERR_NOT_ENOUGH_UNCLAIMED_RESOURCE: -17,
    STRUCTURES_ALL: [STRUCTURE_CONTAINER, STRUCTURE_CONTROLLER, STRUCTURE_EXTENSION, STRUCTURE_EXTRACTOR, STRUCTURE_FACTORY, STRUCTURE_INVADER_CORE, STRUCTURE_KEEPER_LAIR, STRUCTURE_LAB, STRUCTURE_LINK, STRUCTURE_NUKER, STRUCTURE_OBSERVER, STRUCTURE_PORTAL, STRUCTURE_POWER_BANK, STRUCTURE_POWER_SPAWN, STRUCTURE_RAMPART, STRUCTURE_ROAD, STRUCTURE_SPAWN, STRUCTURE_STORAGE, STRUCTURE_TERMINAL, STRUCTURE_TOWER, STRUCTURE_WALL,]
}